x-nlp: &nlp
  environment:
    - DISPLAY=${DISPLAY}
    - XAUTHORITY=/home/yarp-user/.Xauthority
    - QT_X11_NO_MITSHM=1
    - DBUS_SESSION_BUS_ADDRESS=unix:path=/run/yarp-user/1000/bus
    - LIBGL_ALWAYS_INDIRECT=0
    - YARP_COLORED_OUTPUT=1
    - NVIDIA_DRIVER_CAPABILITIES=all
    - R1_OBR_REMOTE=${R1_OBR_REMOTE:-origin}
    - R1_OBR_BRANCH=${R1_OBR_BRANCH:-master}
    - TOUR_REMOTE=${TOUR_REMOTE:-origin}
    - TOUR_BRANCH=${TOUR_BRANCH:-master}
  volumes:
    - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
    - "/etc/hosts:/etc/hosts"
    - "${HOME}/.config/credentials/google-credentials/hsp_google.json:/home/yarp-user/.config/google-credential/hsp_google.json"
    - "${HOME}/.config/credentials/azure-credentials/config.env:/home/yarp-user/.env/config.env"
    - "./entrypoints/entrypoint_light.sh:/home/yarp-user/config/.entrypoint_light.sh"
    - "./entrypoints/entrypoint_heavy.sh:/home/yarp-user/config/.entrypoint_heavy.sh"
    - "./entrypoints/entrypoint_empty.sh:/home/yarp-user/config/.entrypoint_empty.sh"
  network_mode: host
  entrypoint: ["sh", "${ENTRY_POINT:-/home/yarp-user/config/.entrypoint_light.sh}"]
  ipc: host
  pid: host
  privileged: true
  security_opt:
    - apparmor:unconfined
  deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

services:

# Images
  r1-talk-ub24-v2.33-master:
    image: elandini84/r1_talk:ub24.04_vcpkg_gccpp_v2.33
    build:
      context: .
      dockerfile: Dockerfile
      args:
          base_img: ubuntu:24.04
          tour_branch: jazzy
          llm_branch: master
          robot_code: /usr/local/src/robot
          user_name: yarp-user
          yarp_version: yarp-3.12
          uid: 1000
          gid: 1000
          google_cloud_version: tags/2025.01.13

# Containers
  r1-talk-ub24-v2.33-master-container:
    image: elandini84/r1_talk:ub24.04_vcpkg_gccpp_v2.33
    <<: *nlp
    container_name: r1-talk-ub24-v2-33-master-container
    command: terminator -g /home/yarp-user/.config/terminator/config
  r1-talk-ub24-v2.33-master-yarprun:
    image: elandini84/r1_talk:ub24.04_vcpkg_gccpp_v2.33
    <<: *nlp
    container_name: r1-talk-ub24-v2-33-master-yarprun
    command: bash -c "yarp conf 192.168.100.10 10000 && yarprun --server /console-llm --log"