x-nlp: &nlp
  environment:
    - DISPLAY=${DISPLAY}
    - XAUTHORITY=/home/yarp-user/.Xauthority
    - QT_X11_NO_MITSHM=1
    - DBUS_SESSION_BUS_ADDRESS=unix:path=/run/yarp-user/1000/bus
    - LIBGL_ALWAYS_INDIRECT=0
    - YARP_COLORED_OUTPUT=1
    - NVIDIA_DRIVER_CAPABILITIES=all
    - R1_OBR_REMOTE=${R1_OBR_REMOTE:-origin}
    - R1_OBR_BRANCH=${R1_OBR_BRANCH:-master}
    - TOUR_REMOTE=${TOUR_REMOTE:-origin}
    - TOUR_BRANCH=${TOUR_BRANCH:-jazzy}
    - ROBOT_CODE=${ROBOT_CODE:-/usr/local/src/robot}
    - AI_MODEL_PATH=/home/yarp-user/models
  volumes:
    - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
    - "/etc/hosts:/etc/hosts"
    - "${HOME}/.config/yarp:/home/yarp-user/.config/yarp:rw"
    - "${HOME}/.config/credentials/google-credentials/hsp_google.json:/home/yarp-user/.config/google-credential/hsp_google.json"
    - "${HOME}/.config/credentials/azure-credentials/config.env:/home/yarp-user/.env/config.env"
    - "${PORCUPINE_CONFIG:-/usr/local/src}/:/usr/local/src/robot/.config/porcupine"
    - "${AI_MODEL_PATH:$HOME}:/home/yarp-user/models:rw"
    - "./entrypoints/entrypoint_light.sh:/home/yarp-user/config/.entrypoint_light.sh"
    - "./entrypoints/entrypoint_heavy.sh:/home/yarp-user/config/.entrypoint_heavy.sh"
    - "./entrypoints/entrypoint_empty.sh:/home/yarp-user/config/.entrypoint_empty.sh"
    - "./entrypoints/entrypoint_porcupine.sh:/home/yarp-user/config/.entrypoint_porcupine.sh"
    - "./entrypoints/entrypoint_cuda.sh:/home/yarp-user/config/.entrypoint_cuda.sh"
  network_mode: host
  entrypoint: ["sh", "${ENTRY_POINT:-/home/yarp-user/config/.entrypoint_cuda.sh}"]
  ipc: host
  pid: host
  privileged: true
  security_opt:
    - apparmor:unconfined
  deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

services:

# Images
  r1-talk-image:
    image: ghcr.io/hsp-iit/r1_talk:${UB_VERSION:-ub24}.04_vcpkg_gccpp_${GCCPP_VERSION:-v2.36}_cuda_${CUDA_VERSION:-12.8}_${BUILD_TYPE:-devel}
    build:
      context: .
      dockerfile: Dockerfile
      args:
          base_img: ${BASE_TALK_IMG:-ubuntu:24.04}
          tour_branch: ${TOUR_BRANCH:-jazzy}
          llm_branch: ${LLM_BRANCH:-master}
          robot_code: ${ROBOT_CODE:-/usr/local/src/robot}
          user_name: yarp-user
          yarp_version: ${YARP_BRANCH:-yarp-3.12}
          uid: 1000
          gid: 1000
          vcpkg_tag: ${VCPKG_TAG:-tags/2025.06.13}
          cuda_version: ${CUDA_VERSION:-12.8}
          ai_model_path: ${AI_MODEL_PATH:-/home/yarp-user/models}

# Containers
  r1-talk-container:
    image: ghcr.io/hsp-iit/r1_talk:${UB_VERSION:-ub24.04}_vcpkg_gccpp_${GCCPP_VERSION:-v2.36}_cuda_${CUDA_VERSION:-12.8}_${BUILD_TYPE:-devel}
    <<: *nlp
    container_name: r1-talk-container
    command: terminator -g /home/yarp-user/.config/terminator/config
  r1-talk-yarprun:
    image: ghcr.io/hsp-iit/r1_talk:${UB_VERSION:-ub24.04}_vcpkg_gccpp_${GCCPP_VERSION:-v2.36}_cuda_${CUDA_VERSION:-12.8}_${BUILD_TYPE:-devel}
    <<: *nlp
    container_name: r1-talk-yarprun
    command: bash -c "yarp conf 192.168.100.10 10000 && yarprun --server /console-llm --log"