bt_navigator:
  ros__parameters:
    use_sim_time: true
    global_frame: map
    robot_base_frame: mobile_base_body_link
    odom_topic: /odometry
    bt_loop_duration: 10
    default_server_timeout: 20
    # 'default_nav_through_poses_bt_xml' and 'default_nav_to_pose_bt_xml' are use defaults:
    # nav2_bt_navigator/navigate_to_pose_w_replanning_and_recovery.xml
    # nav2_bt_navigator/navigate_through_poses_w_replanning_and_recovery.xml
    # They can be set here or via a RewrittenYaml remap from a parent launch file to Nav2.
    plugin_lib_names:
      - nav2_compute_path_to_pose_action_bt_node
      - nav2_compute_path_through_poses_action_bt_node
      - nav2_smooth_path_action_bt_node
      - nav2_follow_path_action_bt_node
      - nav2_spin_action_bt_node
      - nav2_wait_action_bt_node
      - nav2_assisted_teleop_action_bt_node
      - nav2_back_up_action_bt_node
      - nav2_drive_on_heading_bt_node
      - nav2_clear_costmap_service_bt_node
      - nav2_is_stuck_condition_bt_node
      - nav2_goal_reached_condition_bt_node
      - nav2_goal_updated_condition_bt_node
      - nav2_globally_updated_goal_condition_bt_node
      - nav2_is_path_valid_condition_bt_node
      - nav2_are_error_codes_active_condition_bt_node
      - nav2_would_a_controller_recovery_help_condition_bt_node
      - nav2_would_a_planner_recovery_help_condition_bt_node
      - nav2_would_a_smoother_recovery_help_condition_bt_node
      - nav2_initial_pose_received_condition_bt_node
      - nav2_reinitialize_global_localization_service_bt_node
      - nav2_rate_controller_bt_node
      - nav2_distance_controller_bt_node
      - nav2_speed_controller_bt_node
      - nav2_truncate_path_action_bt_node
      - nav2_truncate_path_local_action_bt_node
      - nav2_goal_updater_node_bt_node
      - nav2_recovery_node_bt_node
      - nav2_pipeline_sequence_bt_node
      - nav2_round_robin_node_bt_node
      - nav2_transform_available_condition_bt_node
      - nav2_time_expired_condition_bt_node
      - nav2_path_expiring_timer_condition
      - nav2_distance_traveled_condition_bt_node
      - nav2_single_trigger_bt_node
      - nav2_goal_updated_controller_bt_node
      - nav2_is_battery_low_condition_bt_node
      - nav2_navigate_through_poses_action_bt_node
      - nav2_navigate_to_pose_action_bt_node
      - nav2_remove_passed_goals_action_bt_node
      - nav2_planner_selector_bt_node
      - nav2_controller_selector_bt_node
      - nav2_goal_checker_selector_bt_node
      - nav2_controller_cancel_bt_node
      - nav2_path_longer_on_approach_bt_node
      - nav2_wait_cancel_bt_node
      - nav2_spin_cancel_bt_node
      - nav2_back_up_cancel_bt_node
      - nav2_assisted_teleop_cancel_bt_node
      - nav2_drive_on_heading_cancel_bt_node
      - nav2_is_battery_charging_condition_bt_node
    error_code_names:
      - compute_path_error_code
      - follow_path_error_code

bt_navigator_rclcpp_node:
  ros__parameters:
    use_sim_time: true

controller_server:
  ros__parameters:
    use_sim_time: true
    controller_frequency: 5.0
    min_x_velocity_threshold: 0.01
    min_y_velocity_threshold: 0.5
    min_theta_velocity_threshold: 0.01
    failure_tolerance: 0.3
    speed_limit_topic: /speed_limit
    odom_topic: /odometry
    progress_checker_plugins:
    - progress_checker
    goal_checker_plugins:
    - goal_checker
    controller_plugins:
    - FollowPath

    # Progress checker parameters
    progress_checker:
      plugin: nav2_controller::SimpleProgressChecker
      required_movement_radius: 0.5
      movement_time_allowance: 10.0

    # Goal checker parameters
    goal_checker:
      plugin: nav2_controller::SimpleGoalChecker
      xy_goal_tolerance: 0.2
      yaw_goal_tolerance: 0.15
      stateful: true

    # DWB parameters
    FollowPath:
      plugin: dwb_core::DWBLocalPlanner

      # Generic
      prune_distance: 2.0
      prune_plan: true
      shorten_transformed_plan: true
      debug_trajectory_details: false
      trajectory_generator_name: dwb_plugins::StandardTrajectoryGenerator
      transform_tolerance: 0.2
      short_circuit_trajectory_evaluation: true
      xy_goal_tolerance: 0.1

      # XYTheta Iterator
      vx_samples: 20
      vy_samples: 0
      vtheta_samples: 40

      # Kinematic Parameters
      max_vel_x: 0.4
      max_vel_y: 0.0
      max_vel_theta: 0.6
      min_vel_x: 0.0
      min_vel_y: 0.0
      min_speed_xy: 0.0
      max_speed_xy: 0.4
      min_speed_theta: 0.0
      acc_lim_x: 2.5
      acc_lim_y: 0.0
      acc_lim_theta: 3.2
      decel_lim_x: -2.5
      decel_lim_y: 0.0
      decel_lim_theta: -3.2
      trans_stopped_velocity: 0.01

      # Publisher params
      publish_cost_grid_pc: false
      publish_evaluation: false
      publish_global_plan: true
      publish_local_plan: true
      publish_trajectories: false
      publish_transformed_plan: false
      marker_lifetime: 0.1

      # Trajectory generator
      sim_time: 2.0
      discretize_by_time: false
      time_granularity: 0.5
      linear_granularity: 0.05
      angular_granularity: 0.025
      include_last_point: true

      # Critics
      critics:
      - RotateToGoal
      - Oscillation
      - BaseObstacle
      - GoalAlign
      - PathAlign
      - PathDist
      - GoalDist
      BaseObstacle.scale: 0.02
      BaseObstacle.sum_scores: false

      PathAlign.scale: 32.0
      PathAlign.forward_point_distance: 0.1

      GoalAlign.scale: 24.0
      GoalAlign.forward_point_distance: 0.1

      PathDist.scale: 32.0

      Oscillation.oscillation_reset_angle: 0.2
      Oscillation.oscillation_reset_dist: 0.05
      Oscillation.oscillation_reset_time: -1.0
      Oscillation.scale: 1.0
      Oscillation.x_only_threshold: 0.05

      GoalDist.scale: 24.0

      RotateToGoal.scale: 32.0
      RotateToGoal.slowing_factor: 5.0
      RotateToGoal.lookahead_time: -1.0

controller_server_rclcpp_node:
  ros__parameters:
    use_sim_time: true

local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 6.0
      publish_frequency: 2.0
      global_frame: map
      robot_base_frame: mobile_base_body_link
      use_sim_time: true
      rolling_window: true
      width: 6
      height: 6
      resolution: 0.05
      robot_radius: 0.35
      track_unknown_space: false
      always_send_full_costmap: true
      trinary_costmap: true
      plugins:
      - obstacle_layer
      - voxel_layer
      - inflation_layer
      inflation_layer:
        plugin: nav2_costmap_2d::InflationLayer
        enabled: true
        inflation_radius: 1.0
        cost_scaling_factor: 1.25
        inflate_unknown: false
        inflate_around_unknown: false
      obstacle_layer:
        plugin: nav2_costmap_2d::ObstacleLayer
        enabled: true
        observation_sources: scan
        footprint_clearing_enabled: true
        max_obstacle_height: 1.0
        combination_method: 1
        scan:
          topic: /laser_local
          obstacle_max_range: 5.0
          obstacle_min_range: 0.05
          raytrace_max_range: 20.0
          raytrace_min_range: 0.0
          max_obstacle_height: 1.0
          min_obstacle_height: 0.0
          clearing: true
          marking: true
          data_type: "LaserScan"
          inf_is_valid: false
      voxel_layer:
        plugin: nav2_costmap_2d::VoxelLayer
        enabled: true
        footprint_clearing_enabled: true
        max_obstacle_height: 2.0
        publish_voxel_map: true
        origin_z: 0.0
        z_resolution: 0.2
        z_voxels: 8
        unknown_threshold: 15
        mark_threshold: 2
        observation_sources: pointcloud_mark pointcloud_clear
        combination_method: 1
        pointcloud_mark:  # no frame set, uses frame from message
          topic: /camera/depth/color/points
          max_obstacle_height: 1.8
          min_obstacle_height: 0.2
          obstacle_max_range: 3.0
          obstacle_min_range: 0.2
          raytrace_max_range: 4.0
          raytrace_min_range: 0.0
          clearing: false
          marking: true
          data_type: "PointCloud2"
        pointcloud_clear:  # no frame set, uses frame from message
          topic: /camera/depth/color/points
          max_obstacle_height: 4.8
          min_obstacle_height: -4.8
          obstacle_max_range: 3.0
          obstacle_min_range: 0.0
          raytrace_max_range: 12.0
          raytrace_min_range: 0.0
          clearing: true
          marking: false
          data_type: "PointCloud2"
      filters: ["keepout_filter"]
      keepout_filter:
        plugin: "nav2_costmap_2d::KeepoutFilter"
        enabled: True
        filter_info_topic: "/costmap_filter_info"
  local_costmap_client:
    ros__parameters:
      use_sim_time: true
  local_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: true

global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 2.0
      publish_frequency: 0.5
      global_frame: map
      robot_base_frame: mobile_base_body_link
      use_sim_time: true
      robot_radius: 0.3
      resolution: 0.05
      track_unknown_space: true
      #unknown_cost_value: 100
      always_send_full_costmap: true
      trinary_costmap: true
      plugins:
      - static_layer
      - obstacle_layer
      - inflation_layer
      obstacle_layer:
        plugin: nav2_costmap_2d::ObstacleLayer
        enabled: true
        observation_sources: scan
        footprint_clearing_enabled: true
        max_obstacle_height: 1.0
        combination_method: 1
        scan:
          topic: /laser_local
          obstacle_max_range: 5.0
          obstacle_min_range: 0.05
          raytrace_max_range: 20.0
          raytrace_min_range: 0.0
          max_obstacle_height: 1.0
          min_obstacle_height: 0.0
          clearing: true
          marking: true
          data_type: "LaserScan"
          inf_is_valid: false
      static_layer:
        plugin: nav2_costmap_2d::StaticLayer
        map_subscribe_transient_local: true
        enabled: true
        subscribe_to_updates: true
        transform_tolerance: 0.2
      inflation_layer:
        plugin: nav2_costmap_2d::InflationLayer
        enabled: true
        inflation_radius: 1.0
        cost_scaling_factor: 2.5
        inflate_unknown: false
        inflate_around_unknown: false
      filters: ["keepout_filter"]
      keepout_filter:
        plugin: "nav2_costmap_2d::KeepoutFilter"
        enabled: True
        filter_info_topic: "/costmap_filter_info"
  global_costmap_client:
    ros__parameters:
      use_sim_time: true
  global_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: true

planner_server:
  ros__parameters:
    expected_planner_frequency: 1.0
    use_sim_time: true
    planner_plugins:
    - GridBased
    GridBased:
      plugin: nav2_theta_star_planner/ThetaStarPlanner
      how_many_corners: 8
      w_euc_cost: 1.0
      w_traversal_cost: 2.0
      use_final_approach_orientation: false
      allow_unknown: false

planner_server_rclcpp_node:
  ros__parameters:
    use_sim_time: true

smoother_server:
  ros__parameters:
    use_sim_time: true
    costmap_topic: global_costmap/costmap_raw
    footprint_topic: global_costmap/published_footprint
    robot_base_frame: mobile_base_body_link
    transform_timeout: 0.2
    smoother_plugins:
    - simple_smoother
    simple_smoother:
      plugin: nav2_smoother::SimpleSmoother
      tolerance: 1.0e-10
      max_its: 1000
      do_refinement: true
      w_data: 0.2
      w_smooth: 0.3


behavior_server:
  ros__parameters:
    costmap_topic: local_costmap/costmap_raw
    footprint_topic: local_costmap/published_footprint
    cycle_frequency: 10.0
    behavior_plugins:
    - spin
    - backup
    - drive_on_heading
    - wait
    spin:
      plugin: "nav2_behaviors/Spin"
    backup:
      plugin: "nav2_behaviors/BackUp"
    drive_on_heading:
      plugin: "nav2_behaviors/DriveOnHeading"
    wait:
      plugin: "nav2_behaviors/Wait"
    global_frame: map
    robot_base_frame: mobile_base_body_link
    transform_tolerance: 0.1
    use_sim_time: true
    simulate_ahead_time: 2.0
    max_rotational_vel: 1.0
    min_rotational_vel: 0.4
    rotational_acc_lim: 3.2

waypoint_follower:
  ros__parameters:
    loop_rate: 20
    stop_on_failure: false
    waypoint_task_executor_plugin: wait_at_waypoint
    wait_at_waypoint:
      plugin: nav2_waypoint_follower::WaitAtWaypoint
      enabled: true
      waypoint_pause_duration: 200
