name: Docker build secondary

on:
  schedule:
  - cron: "0 2 * * 2,4"
  workflow_dispatch:

jobs:
  build-talk-docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
         config:
         - {
            work_dir: "docker_stuff/docker_talk/",
            base_image: "ubuntu:24.04",
            ubuntu_version: "ub24",
            vcpkg_tag: "tags/2025.06.13",
            gcpp_version: "v2.36"
         }
    steps:
    - name: Info
      run: |
       echo "Event type: ${{github.event_name}}"
    - name: Change Docker to experimental mode
      run: |
       sudo rm -rf /etc/docker/daemon.json
       echo '{"experimental": true}' | sudo tee -a /etc/docker/daemon.json
    - name: Restart Docker daemon
      run: sudo systemctl restart docker
    - uses: actions/checkout@v6
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v4
      with:
       registry: ghcr.io
       username: ${{ github.actor }}
       password: ${{ secrets.GITHUB_TOKEN }}
    - name: Free disk space
      run: sudo rm -rf /opt/hostedtoolcache
    - name: Build and push Docker talk image
      uses: docker/build-push-action@v5
      with:
        context: ${{ matrix.config.work_dir }}
        file: ${{ matrix.config.work_dir }}/Dockerfile
        build-args: |
          base_img=${{ matrix.config.base_image }}
          cuda_version=${{ matrix.config.cuda_version }}
          ubuntu_version=${{ matrix.config.ubuntu_version }}
          vcpkg_tag=${{ matrix.config.vcpkg_tag }}
        push: true
        outputs: type=registry
        tags: |
          ghcr.io/${{ github.repository_owner }}/r1_talk:${{ matrix.config.ubuntu_version }}.04_vcpkg_gccpp_${{ matrix.config.gcpp_version }}-${{ github.event_name == 'schedule' && 'devel' || 'stable' }}

  build-cuda-docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
         config:
         - {
            work_dir: "docker_stuff/docker_tourCore_cuda_custom",
            base_image: "ghcr.io/hsp-iit/r1images:tourCore2_ubuntu24.04_jazzy_",
            cuda_version: "12.8",
            base_image_label: "ubuntu24.04_jazzy"
         }
    steps:
    - name: Info
      run: |
       echo "Event type: ${{github.event_name}}"
    - name: Change Docker to experimental mode
      run: |
       sudo rm -rf /etc/docker/daemon.json
       echo '{"experimental": true}' | sudo tee -a /etc/docker/daemon.json
    - name: Restart Docker daemon
      run: sudo systemctl restart docker
    - uses: actions/checkout@v6
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v4
      with:
       registry: ghcr.io
       username: ${{ github.actor }}
       password: ${{ secrets.GITHUB_TOKEN }}
    - name: Free disk space
      run: sudo rm -rf /opt/hostedtoolcache
    - name: Build and push tourCore2 Docker image
      uses: docker/build-push-action@v5
      with:
        context: ${{ matrix.config.work_dir }}
        file: ${{ matrix.config.work_dir }}/Dockerfile
        build-args: |
          base_img=${{ matrix.config.base_image }}${{ github.event_name == 'schedule' && 'devel' || 'stable' }}
          cuda_version=${{ matrix.config.cuda_version }}
        push: true
        outputs: type=registry
        tags: |
          ghcr.io/${{ github.repository_owner }}/r1images:tourCore2_${{ matrix.config.base_image_label }}_cuda_${{ matrix.config.cuda_version }}_${{ github.event_name == 'schedule' && 'devel' || 'stable' }}

  build-cuda-sim-docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
         config:
         - {
            work_dir: "docker_stuff/docker_tourCore_cuda_custom",
            base_image: "ghcr.io/hsp-iit/r1images:tourSim2_ubuntu24.04_jazzy_",
            cuda_version: "12.8",
            base_image_label: "ubuntu24.04_jazzy"
         }
    steps:
    - name: Info
      run: |
       echo "Event type: ${{github.event_name}}"
    - name: Change Docker to experimental mode
      run: |
       sudo rm -rf /etc/docker/daemon.json
       echo '{"experimental": true}' | sudo tee -a /etc/docker/daemon.json
    - name: Restart Docker daemon
      run: sudo systemctl restart docker
    - uses: actions/checkout@v6
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v4
      with:
       registry: ghcr.io
       username: ${{ github.actor }}
       password: ${{ secrets.GITHUB_TOKEN }}
    - name: Free disk space
      run: sudo rm -rf /opt/hostedtoolcache
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ${{ matrix.config.work_dir }}
        file: ${{ matrix.config.work_dir }}/Dockerfile
        build-args: |
          base_img=${{ matrix.config.base_image }}${{ github.event_name == 'schedule' && 'devel' || 'stable' }}
          cuda_version=${{ matrix.config.cuda_version }}
        push: true
        outputs: type=registry
        tags: |
          ghcr.io/${{ github.repository_owner }}/r1images:tourSim2_${{ matrix.config.base_image_label }}_cuda_${{ matrix.config.cuda_version }}_${{ github.event_name == 'schedule' && 'devel' || 'stable' }}

